POST http://localhost:8080/offer
Content-Type: application/json

{
  "message": "i am here!3"
}

###

GET http://localhost:8080/peekMax
Accept: application/json

###

GET http://localhost:8080/peek
Accept: application/json

###
GET http://localhost:8080/poll
Accept: application/json

###

GET http://localhost:8080/all
Accept: application/json

###


